frontendPolicies:
  accessLog:
    add:
      user: request.headers["user-agent"]

llm:
  policies:
    jwtAuth:
      issuer: agentgateway.dev
      audiences: [test.agentgateway.dev]
      jwks: '{"keys":[]}'
    authorization:
      rules:
      - 'jwt.email.endsWith("@example.com")'
  models:
  - name: claude-3-haiku
    provider: anthropic
    params:
      model: claude-haiku-4-5-20251001
      apiKey: "sk-123"
      hostOverride: anthropic.internal:8443
      pathOverride: /v1/messages
      tokenize: true
    responseHeaders:
      remove:
      - server
    backendTLS: {}
    health:
      unhealthyExpression: "response.code >= 500 || response.code == 429"
      eviction:
        duration: 30s
    matches:
    - headers:
      - name: "X-Org"
        value:
          exact: "engineering"
  - name: gemini-0.5-pro
    provider: vertex
    params:
      model: claude-haiku-4-5-20251001
      apiKey: "sk-123"
      vertexRegion: global
      vertexProject: my-vertex-project
  - name: gpt-7-max
    provider: azure
    params:
      model: gpt-3.5-turbo
      azureResourceName: my-azure-openai-endpoint
      azureResourceType: openAI
      azureApiVersion: v1
  - name: gpt-3.5-turbo
    provider: openAI
