binds:
- port: 8080
  tunnelProtocol: direct
  listeners:
  - protocol: HTTP
    name: listener
    hostname: '*'
    routes:
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends:
      - ai:
          name: smallthinker-backend
          provider:
            openAI:
              model: smallthinker
          hostOverride: localhost:11434
      - mcp:
          targets: []
          statefulMode: stateless
        weight: 1
      name: route
      policies:
        cors:
          allowCredentials: false
          allowHeaders:
          - '*'
          allowMethods:
          - GET
          - POST
          - OPTIONS
          allowOrigins:
          - '*'
          exposeHeaders: []
llm:
  models: []
  policies:
    jwtAuth:
      issuer: ''
      audiences: []
      jwks: '{"keys":[]}'
    basicAuth:
      htpasswd: ''
    apiKey:
      keys: []
    authorization:
      rules: []
    transformations: {}
mcp:
  targets: []
  policies:
    cors: {}
    apiKey:
      keys: []
