binds:
  - port: 8080
    tunnelProtocol: direct
    listeners:
      - protocol: HTTP
        name: listener
        hostname: "*"
        routes:
          - hostnames: []
            matches:
              - path:
                  pathPrefix: /
            backends:
              - ai:
                  name: ollama
                  hostOverride: localhost:11434
                  tokenize: false
                  provider:
                    openAI:
                      model: smallthinker
                weight: 1
            name: route
            policies:
              cors:
                allowCredentials: false
                allowHeaders:
                  - "*"
                allowMethods:
                  - GET
                  - POST
                  - OPTIONS
                allowOrigins:
                  - "*"
                exposeHeaders: []
  - port: 8081
    listeners:
      - routes:
          - backends:
              - mcp:
                  targets:
                    - name: everything
                      stdio:
                        cmd: npx
                        args:
                          - "@modelcontextprotocol/server-everything"
            policies:
              cors:
                allowOrigins:
                  - "*"
                allowHeaders:
                  - mcp-protocol-version
                  - content-type
                  - cache-control
                exposeHeaders:
                  - Mcp-Session-Id
