binds:
- port: 30303
  tunnelProtocol: direct
  listeners:
  - protocol: HTTP
    name: asdf
    hostname: '*'
    routes:
    - backends:
      - mcp:
          targets:
          - name: time
            stdio:
              cmd: uvx
              args:
              - mcp-server-time
          - name: everything
            stdio:
              cmd: npx
              args:
              - '@modelcontextprotocol/server-everything'
          statefulMode: stateless
        weight: 3
      policies:
        requestHeaderModifier: {}
        responseHeaderModifier: {}
        transformations: {}
- port: 8080
  tunnelProtocol: direct
  listeners: []
- port: 8083
  tunnelProtocol: direct
  listeners: []
llm:
  port: 1223
  models:
  - name: model-1234
    provider: openAI
    requestHeaders:
      remove: []
    guardrails:
      request: []
      response: []
    matches: []
mcp:
  port: 23
  targets:
  - name: target-1232
    stdio:
      cmd: echo
      args: []
  statefulMode: stateless
frontendPolicies: {}
