/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Owned version of Executor for JSON serialization/deserialization.
 *
 * `ExecutorSerde` is a fully-owned representation that can be deserialized from JSON,
 * stored, and later converted to an `Executor<'_>` for use with CEL expressions.
 *
 * JSON -> ExecutorSerde -> Executor<'_> -> CEL -> JSON should be consistent.
 */
export interface ExecutorSerde {
  /**
   * `request` contains attributes about the incoming HTTP request
   */
  request?: {
    /**
     * The HTTP method of the request. For example, `GET`
     */
    method?: string;
    /**
     * The complete URI of the request. For example, `http://example.com/path`.
     */
    uri?: string;
    /**
     * The hostname of the request. For example, `example.com`.
     */
    host?: string | null;
    /**
     * The scheme of the request. For example, `https`.
     */
    scheme?: string | null;
    /**
     * The path of the request URI. For example, `/path`.
     */
    path?: string;
    /**
     * The version of the request. For example, `HTTP/1.1`.
     */
    version?: string;
    /**
     * The headers of the request.
     */
    headers?: {
      [k: string]: string;
    };
    /**
     * The body of the request. Warning: accessing the body will cause the body to be buffered.
     */
    body?: string | null;
    /**
     * The time the request started
     */
    startTime?: string | null;
    /**
     * The time the request completed
     */
    endTime?: string | null;
  } | null;
  /**
   * `response` contains attributes about the HTTP response
   */
  response?: {
    /**
     * The HTTP status code of the response.
     */
    code?: number;
    /**
     * The headers of the response.
     */
    headers?: {
      [k: string]: string;
    };
    /**
     * The body of the response. Warning: accessing the body will cause the body to be buffered.
     */
    body?: string | null;
  } | null;
  /**
   * `jwt` contains the claims from a verified JWT token. This is only present if the JWT policy is enabled.
   */
  jwt?: {
    [k: string]: unknown;
  } | null;
  /**
   * `apiKey` contains the claims from a verified API Key. This is only present if the API Key policy is enabled.
   */
  apiKey?: {
    key: string;
    [k: string]: unknown;
  } | null;
  /**
   * `basicAuth` contains the claims from a verified basic authentication Key. This is only present if the Basic authentication policy is enabled.
   */
  basicAuth?: {
    username: string;
  } | null;
  /**
   * `llm` contains attributes about an LLM request or response. This is only present when using an `ai` backend.
   */
  llm?: {
    /**
     * Whether the LLM response is streamed.
     */
    streaming: boolean;
    /**
     * The model requested for the LLM request. This may differ from the actual model used.
     */
    requestModel: string;
    /**
     * The model that actually served the LLM response.
     */
    responseModel?: string | null;
    /**
     * The provider of the LLM.
     */
    provider: string;
    /**
     * The number of tokens in the input/prompt.
     */
    inputTokens?: number | null;
    /**
     * The number of tokens in the input/prompt read from cache (savings)
     */
    cachedInputTokens?: number | null;
    /**
     * Tokens written to cache (costs)
     * Not present with OpenAI
     */
    cacheCreationInputTokens?: number | null;
    /**
     * The number of tokens in the output/completion.
     */
    outputTokens?: number | null;
    /**
     * The number of reasoning tokens in the output/completion.
     */
    reasoningTokens?: number | null;
    /**
     * The total number of tokens for the request.
     */
    totalTokens?: number | null;
    /**
     * The number of tokens in the request, when using the token counting endpoint
     * These are not counted as 'input tokens' since they do not consume input tokens.
     */
    countTokens?: number | null;
    /**
     * The prompt sent to the LLM. Warning: accessing this has some performance impacts for large prompts.
     */
    prompt?:
      | {
          role: string;
          content: string;
        }[]
      | null;
    /**
     * The completion from the LLM. Warning: accessing this has some performance impacts for large responses.
     */
    completion?: string[] | null;
    /**
     * The parameters for the LLM request.
     */
    params: {
      temperature?: number | null;
      top_p?: number | null;
      frequency_penalty?: number | null;
      presence_penalty?: number | null;
      seed?: number | null;
      max_tokens?: number | null;
      encoding_format?: string | null;
      dimensions?: number | null;
      [k: string]: unknown;
    };
  } | null;
  /**
   * `llm_request` contains the raw LLM request before processing. This is only present *during* LLM policies;
   * policies occurring after the LLM policy, such as logs, will not have this field present even for LLM requests.
   */
  llmRequest?: {
    [k: string]: unknown;
  };
  /**
   * `source` contains attributes about the source of the request.
   */
  source?: {
    /**
     * The IP address of the downstream connection.
     */
    address?: string;
    /**
     * The port of the downstream connection.
     */
    port?: number;
    /**
     * The (Istio SPIFFE) identity of the downstream connection, if available.
     */
    identity?: {
      /**
       * The trust domain of the identity.
       */
      trustDomain: string;
      /**
       * The namespace of the identity.
       */
      namespace: string;
      /**
       * The service account of the identity.
       */
      serviceAccount: string;
    } | null;
    /**
     * The subject alt names from the downstream certificate, if available.
     */
    subjectAltNames?: string[];
    /**
     * The issuer from the downstream certificate, if available.
     */
    issuer?: string;
    /**
     * The subject from the downstream certificate, if available.
     */
    subject?: string;
    /**
     * The CN of the subject from the downstream certificate, if available.
     */
    subjectCn?: string | null;
  } | null;
  /**
   * `mcp` contains attributes about the MCP request.
   */
  mcp?:
    | (
        | {
            tool: {
              /**
               * The target of the resource
               */
              target?: string;
              /**
               * The name of the resource
               */
              name?: string;
              [k: string]: unknown;
            };
          }
        | {
            prompt: {
              /**
               * The target of the resource
               */
              target?: string;
              /**
               * The name of the resource
               */
              name?: string;
              [k: string]: unknown;
            };
          }
        | {
            resource: {
              /**
               * The target of the resource
               */
              target?: string;
              /**
               * The name of the resource
               */
              name?: string;
              [k: string]: unknown;
            };
          }
      )
    | null;
  /**
   * `backend` contains information about the backend being used.
   */
  backend?: {
    /**
     * The name of the backend being used. For example, `my-service` or `service/my-namespace/my-service:8080`.
     */
    name?: string;
    /**
     * The type of backend. For example, `ai`, `mcp`, `static`, `dynamic`, or `service`.
     */
    type?: "ai" | "mcp" | "static" | "dynamic" | "service" | "unknown";
    /**
     * The protocol of backend. For example, `http`, `tcp`, `a2a`, `mcp`, or `llm`.
     */
    protocol?: "http" | "tcp" | "a2a" | "mcp" | "llm";
  } | null;
  /**
   * `extauthz` contains dynamic metadata from ext_authz filters
   */
  extauthz?: {
    [k: string]: unknown;
  } | null;
  /**
   * `extproc` contains dynamic metadata from ext_proc filters
   */
  extproc?: {
    [k: string]: unknown;
  } | null;
  /**
   * `metadata` contains values set by transformation metadata expressions.
   */
  metadata?: {
    [k: string]: unknown;
  } | null;
}
